# baseURL: https://manual.scientific-python.org
languageCode: en-us
theme: scientific-python-hugo-theme
relativeURLs: true
disableKinds: ["term", "taxonomy"]

languages:
  en:
    title: Scientific Python Manual
    contentDir: content/en
