baseURL: "https://theme.scientific-python.org/"
languageCode: "en-us"
title: "Scientific Python Manual"
theme: scientific-python-hugo-theme
relativeURLs: true
disableKinds: ["term", "taxonomy"]

params:
  description: "How-to's and best practices for scientific Python projects."
  images:
  - /images/logo.svg
  navbarlogo:
    image: logo.svg
    text: Scientific Python manual
    link: /
  hero:
    title: Scientific Python Manual
    subtitle: How-tos and best practices for the scientific Python ecosystem
    buttontext: Learn more
    buttonlink: /getstarted/
    image: logo.svg
# TODO: activate me
  navbar:
    - title: GitHub
      url: https://github.com/scientific-python/scientific-python-hugo-theme
# TODO: activate me
  keyfeatures:
    features:
      - title: Documented
        text: The theme is documented at https://theme.scientific-python.org.
      - title: Reusable
        text: The theme is being used by NumPy, SciPy, ...
      - title: Community Maintained
        text: The theme is maintained by the [Theme Team](https://github.com/orgs/scientific-python/teams/theme-team)
# TODO: activate me
  footer:
    logo: logo.svg
    socialmediatitle: ""
    socialmedia:
      - link: https://github.com/scientific-python/
        icon: github
    quicklinks:
      column1:
        title: ""
        links:
          - text: Scientific Python Forum
            link: https://discuss.scientific-python.org
      column2:
        links:
          - text: Theme GitHub
            link: https://github.com/scientific-python/scientific-python-hugo-theme
      column3:
        links:
